### ISSUE TITLE
support for titanfall 2 in apex toolbox automatic shader when?

### ISSUE THREAD

**Issue by SinOfHyped** [Gl2imm/Apex-Toolbox#2]
pls

**Comment by Gl2imm** [comment]
> pls

Still people use it for TF2? ))
Currently recolor tab is supports TF2. Try it. Just select the folder with TF2 textures and Recolor it. 
Textures must be same as apex, each body part in a separate folder. Images must be same name as material slots, it will work.. (Some textures are white in the video because i did not find that textures)

https://user-images.githubusercontent.com/69973491/198937212-9f959015-6a45-4d70-b1be-ef6b00bebab9.mp4
